export const BANKS = [
  { id: 'bolivariano', name: 'Banco Bolivariano' },
  { id: 'austro', name: 'Banco del Austro' },
  { id: 'pacifico', name: 'Banco del Pacífico' },
  { id: 'guayaquil', name: 'Banco de Guayaquil' },
  { id: 'solidario', name: 'Banco Solidario' },
  { id: 'internacional', name: 'Banco Internacional' },
  { id: 'pichincha', name: 'Banco Pichincha' },
  { id: 'procredit', name: 'Banco ProCredit' },
  { id: 'banecuador', name: 'BanEcuador' },
  { id: 'jardin-azuayo', name: 'Cooperativa Jardín Azuayo' },
  { id: 'jep', name: 'Cooperativa JEP' },
  { id: 'produbanco', name: 'Produbanco' },
  { id: 'general-ruminahui', name: 'Banco General Rumiñahui' },
  { id: 'loja', name: 'Banco de Loja' },
  { id: 'machala', name: 'Banco de Machala' },
  { id: 'amazonas', name: 'Banco Amazonas' },
  { id: 'diners', name: 'Diners Club' },
  { id: 'mutualista-pichincha', name: 'Mutualista Pichincha' },
  { id: 'coop-policia', name: 'Cooperativa Policía Nacional' },
  { id: 'coop-29-octubre', name: 'Cooperativa 29 de Octubre' },
  { id: 'coop-cooprogreso', name: 'Cooperativa Cooprogreso' },
  { id: 'nequi', name: 'Nequi' },
  { id: 'otro', name: 'Otro' },
]
